apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db-mysql.fullname" . }}
spec:
  storageClassName: nfs-standard
  accessModes:
  - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
  volumeMode: Filesystem