# Default values for db-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  tag: 5.7
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort:
  name: dbport
  port: 3306

service:
  type: NodePort
  port: 3306
  #nodePort: 32766

ingress:
  enabled: false

volume:
  capacity: 10Gi
  accessMode: ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  dynamic: true 
  #server: 169.56.88.117
  #path: /data/nfs/mysql-bizlogic

resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 100Mi
